file:
    upload-dir: /home/ubuntu/upload
logging:
    file:
        name: /logs/lotteon.log
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: info
                sql: debug
            mybatis: error
            springframework:
                security: debug
                web: error
        root: info
server:
    error:
        whitelabel:
            enabled: false
    port: 8080
spring:
    config :
        import:
            - optional:classpath:application-local.yml
            - optional:classpath:application-ec2.yml


